name: Flutter CI

on:
  pull_request:
    branches:
      - main

  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
          flutter-version: "2.8.1"
      - run: flutter pub get
      - run: flutter build apk --debug --split-per-abi
      ##- uses: actions/upload-artifact@v1
      - uses: ncipollo/release-action@v1
        with:
          ##name: release-apk
          artifacts: "build/app/outputs/apk/debug/*"
          ##path: build/app/outputs/apk/release/app-release.apk
          tag:  v1.0.${{ github.run_number }}
          token: ${{ secrets.GIT_TOKEN}}
          
      - name: Upload to slack step
      - uses: adrey/slack-file-upload-action@master
        ##- uses: actions/upload-artifact@v3
        with:
          token: ${{ secrets.SLACK_TOKEN }}
          path: build/app/outputs/apk/debug/app-armeabi-v7a-debug.apk
          channel-id: 'C02EKNP8JQH'

      - uses: slackapi/slack-github-action@v1.18.0
        with:
          channel-id: 'C02EKNP8JQH'
          slack-message: "Does it Work"
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_TOKEN }}


